apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-05-31T08:04:58Z"
  generation: 1
  labels:
    app: product-api
  name: product-api
  namespace: coffeeshop
  resourceVersion: "1270"
  uid: c29c2b79-f604-4973-a349-a316c82b8680
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: product-api
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: product-api
        image: k3d-myregistry.localhost:12345/product-api:latest
        imagePullPolicy: IfNotPresent
        name: product-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 180
status:
  conditions:
  - lastTransitionTime: "2024-05-31T08:04:58Z"
    lastUpdateTime: "2024-05-31T08:04:58Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-05-31T08:04:58Z"
    lastUpdateTime: "2024-05-31T08:04:58Z"
    message: ReplicaSet "product-api-788f967db8" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
